define:
  paging:
    defaultSize: 15      #默认分页大小
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.139:8888/eureka/   #连接的 eureka 服务器地址
spring:
  cloud:
    stream:
      kafka:
        binder:
          zk-nodes: 192.168.1.34
          brokers: 192.168.1.34
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.1.34
    port: 5672
    username: admin
    password: admin123
#  zipkin:
#    enabled: false
#    base-url: http://192.168.1.119:9411
#  sleuth:
#    sampler:
#      percentage: 0.1
ribbon:
  ConnectTimeout: 3000     #ribbon 负载均衡连接超时时间
  ReadTimeout: 60000       #ribbon 负载均衡读取超时时间
logging:
  level:
    com.naju: debug
  file: D:\Logs\com\naju\${spring.application.name}.log