server:
  port: 9999
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yanglangfei/config    #远程存储库的URI。
          search-paths: /src/main/resources/config       #在本地工作副本中使用的搜索路径。默认情况下只搜索根。
          username: 185601452@qq.com      #用于远程存储库的身份验证用户名。
          password: wz5899117                    #	使用远程存储库验证密码。
          basedir: target/config                  #库的本地工作副本的基本目录。





    stream:
      kafka:
        binder:
          brokers: 192.168.1.34           #Kafka活页夹将连接的经纪人列表。  默认localhost
          zkNodes: 192.168.1.34          #Kafka绑定器可以连接的ZooKeeper节点列表。
          zk-connection-timeout: 10000     #Kafka连接超时时间
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.1.34
    port: 5672
    username: admin
    password: admin123
eureka:
  instance:
    refer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
  client:
      register-with-eureka: false   #是否自动注册到服务中心，默认true
      fetch-registry: false          #是否从注册中心获取注册列表  默认true
management:
  security:
    enabled: false
logging:
  file: D:\Logs\com\config.log
  level:
    com.naju: debug